# Generated by Django 3.2.18 on 2023-03-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('A#', 'A#'), ('B', 'B'), ('C', 'C'), ('C#', 'C'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#')], max_length=2)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, max_length=1)),
            ],
        ),
    ]
