# Generated by Django 3.2.18 on 2023-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictranscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='clef',
            field=models.CharField(default='treble', max_length=6),
        ),
    ]
